### ISSUE TITLE
Building u-boot from source breaks things

### ISSUE THREAD

**Issue by tytydraco** [MiyooCFW/sdcard#9]
I'd like to vote for the revert of 388ae6ecd02a9615c97b1202030fea7778cae1dc, and a redo of it:
* Adds `.idea` folder, which is IDE files that should be gitignored
* Sets default device to bitboy, which is NOT what the wiki says
* Breaks builds for v90_q90, even after setting platform back in /boot/console.cfg and in the generate script. gmenu2 segfaults according to my logs.

We should revert this ASAP and redo it cleaner.

**Comment by tytydraco** [comment]
I can confirm that reverting this commit fixes the build for my device (Q90 and V90).

**Comment by tiopex** [comment]
Hi @tytydraco,

These two issues has been fixed:

> * Adds `.idea` folder, which is IDE files that should be gitignored
> * Sets default device to bitboy, which is NOT what the wiki says

Regarding this, we unable to reproduce it. Could you please check on the latest. If the issue still exist I can prepare testing version.

> * Breaks builds for v90_q90, even after setting platform back in /boot/console.cfg and in the generate script. gmenu2 segfaults according to my logs.
> 

Regards

**Comment by Phanuphongza** [comment]
ด่รด
